# Generated by Django 4.1.3 on 2022-11-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_api_app', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
