# Generated by Django 4.1.3 on 2022-11-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_api_app', '0003_order_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.TextField(max_length=100),
        ),
    ]
