# Generated by Django 4.1.3 on 2022-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_api_app', '0004_alter_order_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.TextField(max_length=100)),
                ('cheese', models.TextField(max_length=100)),
                ('meat', models.TextField(max_length=100)),
                ('chicken', models.TextField(max_length=100)),
            ],
        ),
    ]
