# Generated by Django 4.1.3 on 2022-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_api_app', '0005_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='order',
            name='cheese',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='chicken',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='meat',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
